chore: upgrade tdesign-miniprogram version to 1.0.0-rc
Tencent/tdesign-miniprogram-starter-retail pull request #66
Opened 2023-01-18 08:43 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- - chore: 升级 tdesign-miniprogram 组件库版本到 1.0.0-rc

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-01-18 09:11 UTC, LeeJim requested changes

2023-01-18 09:11 UTC, LeeJim commented on pages/goods/details/index.wxml
> +      height="750rpx"
用 100 vh 比较好

2023-01-18 09:11 UTC, LeeJim commented on pages/goods/list/index.wxml
> +            align="center"
代码格式有问题

2023-01-18 09:11 UTC, LeeJim commented on pages/order/after-service-detail/index.wxml
> +            align="top"
代码格式有问题？

2023-01-18 09:36 UTC, anlyyao commented on model/swiper.js
> +// const images = [
t-swiper 目前的数据格式是， ['imgSrc', '...']，加上这里也只用到了图片地址这一个字段， 就暂时直接修改数据格式了

2023-01-18 09:38 UTC, anlyyao commented on pages/goods/details/index.wxml
> +      height="750rpx"
但这里不是全屏 只有是750rpx、、

2023-01-18 09:39 UTC, anlyyao commented on pages/goods/list/index.wxml
> +            align="center"
1 我改一下格式化配置文件，顺便把 spell-check 也加进去

2023-02-01 10:26 UTC, anlyyao commented
@LeeJim 格式化问题已处理，单词拼写问题已处理

2023-02-02 07:32 UTC, LeeJim approved these changes

2023-02-02 07:33 UTC, merged